#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FIRST_SOURCE="${1:-$FRONTEND_DIR/public/scroll-world/quanfora/first-scene.mp4}"
SECOND_SOURCE="${2:-$FRONTEND_DIR/public/scroll-world/quanfora/seconde-scene.mp4}"
THIRD_SOURCE="${3:-$FRONTEND_DIR/public/scroll-world/quanfora/third-scene.mp4}"
FOURTH_SOURCE="${4:-$FRONTEND_DIR/public/scroll-world/quanfora/fourth-scene.mp4}"
OUTPUT_DIR="${5:-$FRONTEND_DIR/public/scroll-world/quanfora/scenes}"
COMPOSITOR="$SCRIPT_DIR/composite-scroll-world-checkerboard.py"
FRAME_RATE=24

for source_path in "$FIRST_SOURCE" "$SECOND_SOURCE" "$THIRD_SOURCE" "$FOURTH_SOURCE"; do
  if [[ ! -f "$source_path" ]]; then
    echo "Scroll-world source not found: $source_path" >&2
    exit 1
  fi
done

for command_name in ffmpeg ffprobe python3; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    echo "Required command is not available: $command_name" >&2
    exit 1
  fi
done

python3 -c "import PIL, numpy, scipy" >/dev/null 2>&1 || {
  echo "The scene compositor requires Pillow, NumPy, and SciPy." >&2
  exit 1
}

mkdir -p "$OUTPUT_DIR"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/quanfora-scenes.XXXXXX")"
trap 'rm -rf "$WORK_DIR"' EXIT

encode_scene() {
  scene_number="$1"
  scene_slug="$2"
  frames_dir="$3"
  clip_path="$OUTPUT_DIR/scene-$scene_number-$scene_slug.mp4"
  poster_path="$OUTPUT_DIR/scene-$scene_number-$scene_slug.jpg"

  ffmpeg -hide_banner -loglevel error -y \
    -framerate "$FRAME_RATE" -i "$frames_dir/frame-%05d.png" -an \
    -c:v libx264 -preset slow -crf 20 -pix_fmt yuv420p \
    -g 8 -keyint_min 8 -sc_threshold 0 -movflags +faststart "$clip_path"

  ffmpeg -hide_banner -loglevel error -y -i "$clip_path" \
    -frames:v 1 -q:v 2 "$poster_path"
}

build_checkerboard_scene() {
  scene_number="$1"
  scene_slug="$2"
  source_path="$3"
  raw_dir="$WORK_DIR/scene-$scene_number-raw"
  composited_dir="$WORK_DIR/scene-$scene_number-composited"

  mkdir -p "$raw_dir" "$composited_dir"
  ffmpeg -hide_banner -loglevel error -y -i "$source_path" -an \
    -vf "fps=$FRAME_RATE" \
    "$raw_dir/frame-%05d.png"
  python3 "$COMPOSITOR" "$raw_dir" "$composited_dir"
  encode_scene "$scene_number" "$scene_slug" "$composited_dir"
}

build_opaque_scene() {
  scene_number="$1"
  scene_slug="$2"
  frames_dir="$WORK_DIR/scene-$scene_number-opaque"

  mkdir -p "$frames_dir"
  ffmpeg -hide_banner -loglevel error -y -i "$FOURTH_SOURCE" -an \
    -vf "fps=$FRAME_RATE" "$frames_dir/frame-%05d.png"
  encode_scene "$scene_number" "$scene_slug" "$frames_dir"
}

# The first three supplied H.264 files contain a checkerboard as real pixels.
build_checkerboard_scene 01 signal "$FIRST_SOURCE"
build_checkerboard_scene 02 agents "$SECOND_SOURCE"
build_checkerboard_scene 03 risk "$THIRD_SOURCE"
build_opaque_scene 04 decision

# Remove assets generated by the former story mappings.
rm -f \
  "$OUTPUT_DIR/scene-02-evidence.mp4" \
  "$OUTPUT_DIR/scene-02-evidence.jpg" \
  "$OUTPUT_DIR/scene-03-agents.mp4" \
  "$OUTPUT_DIR/scene-03-agents.jpg" \
  "$OUTPUT_DIR/scene-04-risk.mp4" \
  "$OUTPUT_DIR/scene-04-risk.jpg" \
  "$OUTPUT_DIR/scene-05-portfolio.mp4" \
  "$OUTPUT_DIR/scene-05-portfolio.jpg" \
  "$OUTPUT_DIR/scene-06-decision.mp4" \
  "$OUTPUT_DIR/scene-06-decision.jpg"

echo "Built four scroll-world scenes in $OUTPUT_DIR"
