export type WorkspaceWidgetType = "watchlist" | "active_signals" | "price_chart" | "trade_plan" | "policy_check" | "trading_activity" | "account" | "options_chain" | "recent_orders" | "positions";
export type WorkspaceWidgetInstance = { instanceId: string; type: WorkspaceWidgetType; title?: string; position: { x: number; y: number; width: number; height: number }; settings: Record<string, unknown>; linkedToWorkspaceSymbol: boolean; isVisible: boolean };
export type TradingWorkspace = { id: string; name: string; presetType: "paper_trading" | "custom"; basePresetType?: "paper_trading"; isDefault: boolean; layoutVersion: number; selectedSymbol: string; widgets: WorkspaceWidgetInstance[]; createdAt: string; updatedAt: string };
export const WORKSPACE_LAYOUT_VERSION = 2;
const WIDGET_TYPES = new Set<WorkspaceWidgetType>(["watchlist", "active_signals", "price_chart", "trade_plan", "policy_check", "trading_activity", "account", "options_chain", "recent_orders", "positions"]);
export const WIDGET_MIN_SIZE: Record<WorkspaceWidgetType, { width: number; height: number }> = {
  watchlist: { width: 2, height: 4 }, active_signals: { width: 2, height: 3 }, price_chart: { width: 4, height: 5 },
  trade_plan: { width: 3, height: 5 }, policy_check: { width: 3, height: 4 }, trading_activity: { width: 4, height: 4 },
  account: { width: 2, height: 4 }, options_chain: { width: 4, height: 5 }, recent_orders: { width: 2, height: 4 }, positions: { width: 2, height: 4 },
};
export const uid = (prefix = "widget") => `${prefix}-${typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`}`;
export function clampWidget(widget: WorkspaceWidgetInstance): WorkspaceWidgetInstance { const minimum = WIDGET_MIN_SIZE[widget.type] ?? { width: 2, height: 2 }; const width = Math.max(minimum.width, Math.min(12, widget.position.width)); return { ...widget, position: { x: Math.max(0, Math.min(12 - width, widget.position.x)), y: Math.max(0, widget.position.y), width, height: Math.max(minimum.height, Math.min(12, widget.position.height)) } }; }
export function widgetsOverlap(left: WorkspaceWidgetInstance, right: WorkspaceWidgetInstance) { if (!left.isVisible || !right.isVisible) return false; return left.position.x < right.position.x + right.position.width && left.position.x + left.position.width > right.position.x && left.position.y < right.position.y + right.position.height && left.position.y + left.position.height > right.position.y; }
export function normalizeWorkspaceWidgets(widgets: WorkspaceWidgetInstance[]) { return widgets.reduce<WorkspaceWidgetInstance[]>((placed, source) => { let candidate = clampWidget(source); while (candidate.isVisible && placed.some((widget) => widgetsOverlap(candidate, widget))) { const blockers = placed.filter((widget) => widgetsOverlap(candidate, widget)); candidate = { ...candidate, position: { ...candidate.position, y: Math.max(...blockers.map((widget) => widget.position.y + widget.position.height)) } }; } placed.push(candidate); return placed; }, []); }
export function migrateWorkspace(input: unknown, fallback: TradingWorkspace): TradingWorkspace { if (!input || typeof input !== "object") return fallback; const candidate = input as Partial<TradingWorkspace>; const widgets = Array.isArray(candidate.widgets) ? normalizeWorkspaceWidgets(candidate.widgets.filter((widget): widget is WorkspaceWidgetInstance => Boolean(widget && typeof widget === "object" && "type" in widget && WIDGET_TYPES.has((widget as WorkspaceWidgetInstance).type))).map((widget) => clampWidget(widget.type === "price_chart" && widget.settings.chartEngine !== "quanfora" && widget.settings.chartEngine !== "tradingview" ? { ...widget, settings: { ...widget.settings, chartEngine: "tradingview" } } : widget))) : fallback.widgets; return { ...fallback, ...candidate, layoutVersion: WORKSPACE_LAYOUT_VERSION, widgets, updatedAt: new Date().toISOString() } as TradingWorkspace; }
